### ISSUE TITLE
Schema for generated card

### ISSUE THREAD

**Issue by mcfunk** [dennis6p/adaptive-cards-py#16]
How do you generate the schema for a card you create? I am trying to send a card to a powerautomate webhook and it is asking for a schema. Is there a way to do it via the validator?

**Comment by dennis6p** [comment]
Hey @mcfunk, hopefully, I got your question right. You can just make use of the `to_json()` method available for `Card` objects. Does that help already? Normally, you don't need to validate the schema.

**Comment by mcfunk** [comment]
so trying to send a card to powerautomate sends me an error saying that properties are missing, I try to use the sample payload to make the schema on the powerautomate side. I will see what I can find for history and errors.

**Comment by dennis6p** [comment]
Can you tell me a bit more about the error itself? What properties are missing? That would help a lot to trace down the issue. Thanks!

**Comment by mcfunk** [comment]
sorry got distracted today at work. seems like it is the Bolder property. i
can test more tomorrow (today) but in about 9 hours. thanks for the
response, more info to come!

**Comment by mcfunk** [comment]
alright, so it appears it was actually just my mistake, it is working as intended, I tried chasing it back to what mistake I may have made and was unable to figure out quite why it didn't work the first time around. Thanks for the response and thanks for the library !

**Comment by dennis6p** [comment]
Happy to hear that it works now!
