### ISSUE TITLE
MS Teams Full Width Cards

### ISSUE THREAD

**Issue by ghayes** [dennis6p/adaptive-cards-py#26]
There is an adaptive card setting for MS Teams that will force the rendered card to be wider.

"msteams": {  
        "width": "Full"  
    },

Can you add this as a property to AdaptiveCard?

You can see an example from Microsoft here: https://learn.microsoft.com/en-us/answers/questions/932563/can-i-adjust-the-max-width-of-bot-chat-card

**Comment by dennis6p** [comment]
Hey @ghayes,

thanks for reporting this issue. I will take care on it and try to integrate it soon.

**Comment by dennis6p** [comment]
Follow-Up: The official documentation mentions this property as well ([see here](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cdesktop1%2Cdesktop2%2Cconnector-html#full-width-adaptive-card)). Even though it doesn't seem to be an integral part of the actual schema (I can not find it in the schema explorer for cards &rarr; [see `AdaptiveCard`](https://adaptivecards.io/explorer/)), the property exists and can be used in combination with MS Teams. For other frameworks the property is simply ignored and therefore has no effect. It seems reasonable to add it.
