### ISSUE TITLE
Failed to send card: 400, Summary or Text is required

### ISSUE THREAD

**Issue by JanPDreher** [dennis6p/adaptive-cards-py#31]
I have followed the instructions and tried both examples that are contained in the repo.
However, when executing the examples i receive the following runtime error for the "client.send(card)" function. So, executing the "simple_card" example gives me the following output: 
```
python simple_card.py 
Validation was successful: True
Traceback (most recent call last):
  File "/home/.../simple_card.py", line 31, in <module>
    response: Response = client.send(card)
                         ^^^^^^^^^^^^^^^^^
  File "/home/.../.venv/lib/python3.12/site-packages/adaptive_cards/client.py", line 87, in send
    raise RuntimeError(
RuntimeError: Failed to send card: 400, Summary or Text is required.
```

I am not sure where exactly this issue is occuring and where I have to look into in order to fix this.
Does anyone have an idea, what might be the cause?

Just to mention: I did already test my MS Teams incoming webhook successfully using an alternative mehtod, so i think the URL i am using should be fine.

**Comment by dennis6p** [comment]
Hey @JanPDreher,
thanks for opening this issue. May you explain a bit more about how you are using the webhook capability of MS Teams? I just noticed that Incoming Webhook Connectors are about to be phased out at the moment and should be replaced by workflow connectors soon (find more about this topic in the blue-ish box at the top of [__this page__](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet)). And maybe there is a slight difference in how the payload should look like. So how did your messages look while using the alternative method you mentioned?

**Comment by JanPDreher** [comment]
Hey @dennis6p,
thanks for your answer!
Generally, i have a AWS Lambda function which is creating some reporting data (and an image) that i want to publish to an MS Teams channel so users get this information.
When i looked up options to do that, i found the "Incoming Webhook" and i have set it up exactly how it is described in the [link ](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet#create-an-incoming-webhook) you shared. However, i just saw right now that the Incoming Webhook is to be deprecated, so i have to look into the Workflow app and see how this could apply to my use case.

The alternative method i mentioned is some script that a colleague has shared with me. With that i can successfully send a teams post including text. However, since i also want to send images, i have to adapt this somehow, or use an alternative method. That is why i tried to use the "adaptive-cards-py" package.

The code for the alternative mehtod is:
```
def post_teams(header, message):
    headers = {
        'content-type': 'application/json'
    }
 
    teams_post = {
        "type": "message",
        "attachments": [
            {
                "contentType": "application/vnd.microsoft.teams.card.o365connector",
                "contentUrl": None,
                "content": {
                    "@type": "MessageCard",
                    "@context": "https://schema.org/extensions",
                    "summary": "Summary",
                    "title": header,
                    "text": message
                }
            }
        ]
    }
  requests.request('POST', os.environ['TEAMS_INCOMING_WEBHOOK'],  data=json.dumps(teams_post), headers=headers, timeout=30)


post_teams('Test Teams Post from AWS', 'Hello!')
```

**Comment by dennis6p** [comment]
I just found a small issue in the code, which I tried to fix with #32. The field `type` was not added to the payload, when this is created by the Teams client. I don't know, whether this fixes the issue, but it had to be corrected anyway. Maybe give it another try with the new package version.

Regarding the code you posted, there is a small difference in what is actually being sent. With the script from your colleague, one can send a message cards. In contrast, the client from this package will send an adaptive card. Just to make sure, we are on the same page. In general, there are some limitations when it comes to adaptive cards and MS Teams as a target framework. A few of them are listed here: https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#support-for-adaptive-cards

I would recommend to try it once again, while using the workflow approach I just mentioned in my last comment as it seems to be the desired way for the future and probably could solve your issue. I would appreciate any feedback from your side or even further information, such that we can resolve it in some other way.

**Comment by JanPDreher** [comment]
I just updated the adaptive-card-py package to v0.2.1 and now i was able to successfully send a adaptive card. Thanks a lot!

Nevertheless, i will do some research regarding the adaptive cards and try to switch to the workflow approach. (I am not so familiar with the details yet, as i just started working with that.)

Thanks for your help, and quick resolution! I will close the issue here.

**Comment by dennis6p** [comment]
I am glad to hear that!
Yes, I can recommend switching to the workflow approach. From what I understood, this is the way to go in the future. 

Thanks for closing the issue. Let me know, if you need further help in the future!
