### ISSUE TITLE
Cannot add an ActionSet to a Column

### ISSUE THREAD

**Issue by filipvh** [dennis6p/adaptive-cards-py#35]
It seems I cannot add an ActionSet to a Column,
whil this seems to work in other software and is included in examples on adaptivecards.io
example: https://adaptivecards.io/samples/ExpenseReport.html

kr

**Comment by dennis6p** [comment]
Hey @filipvh,

thanks for opening this issue. Can please provide the code which leads to an error? 
What specific layout do you want to build up?

Thanks!

**Comment by filipvh** [comment]
Sorry, good point, it's a type hint issue.

example

```
    topic_action: ActionOpenUrl = ActionOpenUrl(
        title="GOTO",
        url=data.url
    )
    topic_action_set: ActionSet = ActionSet(
        actions=[topic_action]
    )
    topic_action_column: Column = Column(
        items=[topic_action_set],
        width="auto"
    )
```

Expected type 'list[Image | TextBlock | Media | CaptionSource | RichTextBlock] | None', got 'list[ActionSet]' instead 

The code runs fine.
So, nothing critical, but would be nice if this/these case(s) would not give type hint warning.

kr

**Comment by dennis6p** [comment]
Yes, I fully agree. Should be adapted and will be fixed in the PR I mentioned in my last comment. Hopefully, all other parts are working fine for you. Let me know, if you face other issues.
