### ISSUE TITLE
Sending an Image from a local path instead of an URL

### ISSUE THREAD

**Issue by JanPDreher** [dennis6p/adaptive-cards-py#38]
Hi,
i have a usage related question for the adaptive-cards package. I am currently trying to use the adaptive-cards package to send an image that is not publicly available, but rather in my local file system to Teams.

I have tried the example given in the README (section: Adding multiple elements at once) and there sending the Image from an URL works perfectly. 
```
from adaptive_cards.elements import Image
....
image: Image = Image(url="https://adaptivecards.io/content/bf-logo.png")
...
```

For my use case, I am currently trying to figure out if:

- there is any possibility to send an image from a local path instead of the URL?
- If not, would it be possible to upload the image to an AWS S3 Bucket and utliize the S3 URL within the Image(url=) class?
  - i have already tried this, but for some reason the image is not displayed in the adaptive card, but there is only a placeholder. I might have to double-check whether the access permissions of the file are correct...
- Or is the adaptive-cards solution in general not the right fit for my use case?

Thanks already in advance for your support,
Jan

**Comment by dennis6p** [comment]
Hi Jan,

good question. In my opinion, this depends on what you really want to achieve and how large the images are. If your card is only used for displaying a rather small image without any other or only a few more components, then you could try to **[encode it via base64](https://stackoverflow.com/questions/59156265/how-to-encode-a-image-in-python-to-base64)** and add the image content inline. As of my knowledge, that's the closest you can get to "send an image from a local file path". In general, 28KB are the upper size limit of card payloads when sent to teams. Hence, your jsonified card is not allowed to be larger than that. I added a method to the `CardValidator` classes (`card_size(...)`), which will allow you to check the card size upfront. A simple workaround is, to reduce the image size programatically with [__OpenCV__](https://www.tutorialkart.com/opencv/python/opencv-python-resize-image/) or [__PIL__](https://stackoverflow.com/questions/10607468/how-to-reduce-the-image-file-size-using-pil). 

In case you need to display multiple images and your card with an encoded inline image would exceed the size limitation, I rather suggest to reference the image stored somewhere publicly available via its uri. Regarding your approach with uploading a file to AWS, I guess you are right in assuming that missing permission are causing the issue. You somehow have to ensure that the user is allowed to access and display the image. But I actually don't know how permissions are handled in a cross-platform use case with MS Teams and AWS, tbh. Could Azure and its Blob Storage be an alternative for you? And is it for your own usage or should multiple users have access to the image? Have you access to a Sharepoint or OneDrive instance?

**Comment by JanPDreher** [comment]
Hi Dennis,
thanks for your extensive answer!
I will check how well my images can be used given that size limit. Since they are python plots that we create ourselves, it might be enough to add simple plots to the card.
I can also try to use sharepoint, but in this case it is preferred to have everything run on AWS. Anyways, since my use case is still in the exploration/design phase we might decide to use the Teams cards for mostly text based updates and share larger images through another way.
I can give an update later, when i have tried more stuff. However, since you already answered my question i will go ahead and close the topic here :)
Thanks

**Comment by dennis6p** [comment]
Hi Jan,

if it's just about small plots, embedding them could work. Keep me posted about your progress and how you got it working. I would love to hear, which solution you ended up with. :) You can of course open other issues, when there are further questions! 
Thanks!
