### ISSUE TITLE
+r Prevents Validation in Containerised RO Environment.

### ISSUE THREAD

**Issue by YorithTheDreamer** [dennis6p/adaptive-cards-py#39]
A couple weeks ago a bump in validation was made (Great work! Holy jeez!) and the below function was added:
https://github.com/dennis6p/adaptive-cards-py/blob/9b0611e7664e6a94ca4d5a92e04751dfc7bc75da/adaptive_cards/validation.py#L516
```
    def __read_schema_file(self) -> dict[str, Any]:
        with open(
            Path(__file__)
            .parent.joinpath("schemas")
            .joinpath(f"schema-{self.__schema_version}.json"),
            "+r",
            encoding="utf-8",
        ) as f:  # pylint: disable=C0103
            return json.load(f)
```
https://github.com/dennis6p/adaptive-cards-py/commit/14fdab48502316f5dc158a198f5a5c3793a7e357#diff-7b521b205014b14b49f5feda10e253306aebcda4a4e8173d88b8ac8d91b2100fR516

That `+r` implies read _and_ write when only read is needed. On RO filesystems (such as with cloud functions or some containers), this causes the below error:

`OSError: [Errno 30] Read-only file system: '/layers/google.python.pip/pip/lib/python3.10/site-packages/adaptive_cards/schemas/schema-1.5.json`

Please adjust `+r` to simply `r` unless there is a need to write in this read function.

**Comment by dennis6p** [comment]
Hey @YorithTheDreamer,

thanks for reporting the issue. You're right. Read-only would be sufficient in that case. I will take care on it and change it for the next release. I try to be quick with this one. :)

**Comment by dennis6p** [comment]
@YorithTheDreamer The issue is fixed. Thanks a lot for pointing me right to the affected line of code!
Hopefully, this will make it running smooth again on your side with read-only systems. Please let me know, when there are other issues!

**Comment by YorithTheDreamer** [comment]
Thank you for the rapid response and PR! I'd love to have PR permissions to help contribute some clean up here or there to save you time.

**Comment by dennis6p** [comment]
That would be really cool. You can already by just forking and creating a PR from there. I would appreciate your contribution! :)
